### ISSUE TITLE
Pop visualization into new window

### ISSUE THREAD

**Issue by nobillygreen** [datavis-tech/vizhub-ui#49]
As a visualization developer, I want to pop the visualization into a new window so that I have more development room, can utilize multiple monitors, and more easily resize and test reactive visualizations.

Please :+1: this issue to help prioritize this task in our [backlog](https://github.com/datavis-tech/vizhub-ui/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by curran** [comment]
This is possible now with the advent of fullscreen mode #178 .
