### ISSUE TITLE
General Feedback Thread

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-ui#52]
This is a thread for general feedback.

Frustrated using VizHub? We want to know!

Please freely comment here about anything.

**Comment by nitanagdeote** [comment]
have a suggestion .....if there is feature ... like moving cursor on that character in the file will give little info about it ..right on the page as a small pop up.....
for example ..I want to know what is "charset"...and if i hover on it gives short info.

**Comment by curran** [comment]
@nitanagdeote Great ideas!

The links opening in new tabs is tracked as **Open GitHub Links in New Tab** #55

By resizing the page, do you mean resizing the panels within the page?

This is tracked as **IDE - Resizable Editor Pane** #54

**Comment by curran** [comment]
We made the change for opening the GitHub links in new tabs. Thanks for that idea!

**Comment by nitanagdeote** [comment]
Hey...just want to let you know....there is cursor issue...if you zoom out...the cursor disappears...

**Comment by nitanagdeote** [comment]
The intro video could be a link....will save space on the page

**Comment by nitanagdeote** [comment]
See how it looks on the page ....the intro video 
/home/nita/Pictures/Screenshot from 2018-08-17 23-42-16.png

**Comment by nitanagdeote** [comment]
![screenshot from 2018-08-17 23-42-16](https://user-images.githubusercontent.com/13540669/44282075-6c80fa00-a277-11e8-8342-514379f7e836.png)

**Comment by curran** [comment]
@nitanagdeote 
 * Re: video: Ah yes, great point! Thanks for the screenshot it's really helpful.
 * Re: cursor: confirmed I can reproduce the behavior. Created a new issue 98

**Comment by curran** [comment]
@nitanagdeote I figured out how to disable suggestions after the video plays! There's an option in the YouTube embed to turn them off. I updated all the video embeds so they don't show suggestions after playing.

**Comment by nitanagdeote** [comment]
hey....so...when I fork the page....is there anything that says this is the forked page or something.....

**Comment by curran** [comment]
@nitanagdeote Fantastic idea! Made a new issue for that **Forking Confirmation** https://github.com/datavis-tech/vizhub-ui/issues/107

**Comment by nitanagdeote** [comment]
hi....how to delete the file from the list of files in profile...

**Comment by curran** [comment]
Yes that still needs to be implemented. Tracked as **Delete Visualization** #88

**Comment by nitanagdeote** [comment]
......On profile page is it possible to make new file....

**Comment by nitanagdeote** [comment]
suggestion...How about having "hello world" template available in profile or something..

**Comment by curran** [comment]
Great ideas! Tracked as:

 * Create Visualization from Profile Page #121
 * Share Button #122

**Comment by KCachel** [comment]
It would be really awesome if the browser tab was able to pull in the Name of the Visual vs. "Edit Visualization". This would be really helpful when going between them. 
For some similar inspiration check out this blog post:[http://joelcalifa.com/blog/tiny-wins/]( http://joelcalifa.com/blog/tiny-wins/)

**Comment by curran** [comment]
@KCachel That's an excellent idea! Thank you. Tracked as https://github.com/datavis-tech/vizhub-ui/issues/142

**Comment by garrettriha** [comment]
Exporting is an issue for me. After exporting, the index.html for your "Cars Scatter Plot" visualization works. I can make minor tweaks to it through bundle.js (like title name), but if I make any changes in index.js, the code breaks and the html returns an empty page. Also if I try changing anything regarding the data, the code also breaks. This would not be an issue, if the html files from visualizations I create and export from vizhub work. For example I created the project called Garrett R's CitiBike Analysis--it looks great on the vizhub platform, but the exported html does not work. 

Otherwise, Thank you for the tutorial's and awesome source!

**Comment by curran** [comment]
Greetings @garrettriha and thank you for the report!

For the exported HTML to work correctly, you'll need to use a local HTTP server like this command line utility [http-server](https://www.npmjs.com/package/http-server). Are you using a local HTTP server? Just opening the file by double clicking it will open a URL that starts with `file://`, which will not work for loading data files.

To get `bundle.js` to update, you'll need to use the build script included in the exported `package.json`, which uses [Rollup](https://rollupjs.org/) to combine the ES6 modules into a single output file. To use the build script, first run `npm install` in the exported program directory, then run `npm run build`.

I investigated your particular work [G. Riha Citibike & Commuting Analysis](https://vizhub.com/garrettriha/3704472abcf644e79ed15ceda6bd2902) to see if there were any problems with the export workflow. I was able to run the program locally and update `bundle.js` from changes in `index.js` without any issues. The trick is to use the right tools in your development environment.

Here are the exact commands I used in order to get the workflow to work (on Ubuntu Linux):

```
mkdir exportTest
cd exportTest
# Simulate clicking on the link to download the file
wget https://vizhub.com/api/visualization/export/3704472abcf644e79ed15ceda6bd2902 --content-disposition
unzip G.\ Riha\ Citibike\ \&\ Commuting\ Analysis.zip 
npm install -g http-server
http-server
```
Now the program is available at [http://localhost:8080/](http://localhost:8080/).

In a separate terminal window, I ran the following commands to set up the build script:

```
npm install
npm run build
```

Now `bundle.js` is updated. At this point, each time you make a change to a source file, you can run `npm run build` in order to generate a fresh `bundle.js`.

There's a paragraph or so on this topic also in the "Visualization Export" section of [Medium: VizHub 1.0](https://medium.com/@currankelleher/vizhub-1-0-9fc56a70a464).

I realize all these steps are not obvious, and I do have plans to create a documentation page within VizHub itself containing these notes. Thanks for your report though, as it's led to this first draft of the documentation!

If anyone would like to take a stab at implementing this documentation UX, PRs are welcome!

**Comment by garrettriha** [comment]
Hi Curran!

Wow, thank you for the quick and thorough response! You're right my issue
was that I was not using a local HTTP server. Obviously I'm a newbie at
coding, but I've loved your videos and VizHub. I was especially confused
because when I would export your Cars Scatterplot file, and double-click
the html file it worked! Anyways thanks again; I'm enjoying what you're
doing; I love that you're doing it from India; and I wish you the best!

your fan,

Garrett

**Comment by leorawe** [comment]
I am trying to upload a dataset that I found on Cool Datasets.  I converted it to csv from here:
https://raw.githubusercontent.com/hopperrr/ellis-immigration-by-ship/gh-pages/data/trips.tsv
I got to the Upload Dataset page and filled in the blanks.  However, it does not do anything when I hit upload.  I tried a different one, and that one did work.
When I go to: https://vizhub.com/upload-dataset/trips.csv
I gewt: An unexpected error has occurred.

**Comment by leorawe** [comment]
I think I figured it out - Googlesheets did not add "" to strings.  When I did a shorter version and used an online converter, it added strings to my text, and that worked.  Need to find a tsv to csv converter that works for longer data.

**Comment by CleverChuk** [comment]
the "sign up / sign in" prompt takes up a lot of space and is kinda annoying. Can you make that dismissible? Thanks in advance.

**Comment by curran** [comment]
Thanks for the feedback!

**Comment by tasqon** [comment]
Have a look to this visualization [D3 v5 Circle Packing from Observable](https://vizhub.com/tasqon/f7f12b804bbf41d09cbf83b4229c79a3). It is actually kind of template and describes the steps needed to port a (Observable) JavaScript "notebook" into a VizHub vanilla JavaScript index.html

**Comment by curran** [comment]
@tasqon Very cool! I'm thrilled to see things being ported from Observable to VizHub. It means there is hope for VizHub :)

May I suggest setting a custom height for it (by clicking "set height"), so you can see the bottom of the packed circles.

Thanks for sharing!

**Comment by tasqon** [comment]
VizHub is the right meeting point for vanilla D3 JavaScript. No doubt about that.

**Comment by curran** [comment]
The most frequent complaint I see out there about Observable is that it's not vanilla JavaScript, leading to difficulties with exporting and downstream use.

**Comment by tasqon** [comment]
Yes that disturbed me too. The (Observable) Java Script notebooks have a plus and minus side. The big plus I see is that you can share and work with others interactively with Markdown comments in between on one project (notebook). The minus side is that the notebook use the Observable Standard Library and wants its own runtime environment. Hence I asked the Observable folk for the steps required from a (Observable) JavaScript to a vanilla JavaScript. You can follow the discussion when you read the README.md file in this VizHub project [D3 v5 Circle Packing from Observable](https://vizhub.com/tasqon/f7f12b804bbf41d09cbf83b4229c79a3). You need to copy and paste all the fragments manually from the Observable notebook into your index.html, index.js and style.css files. With the right link to the Observable Standard Library. That is fair and fills the gap between vanilla JavaScripts and (Observable) JavaScript notebooks. The point is that a growing number of visualizations by Mike Bostock are only available in new Observable notebooks.

**Comment by PiotrekW2** [comment]
Hi,

I am trying to use impotr, like:
import {cars} from 'cars.js';

but I get some error:
"index.js:5 Uncaught ReferenceError: cars_js is not defined
    at VM1525 about:srcdoc:179"

File cars.js exists:
![image](https://user-images.githubusercontent.com/47700058/52905371-98d2fe80-3239-11e9-88ed-c049edd7ff68.png)

I am beginner and following the Youtube tutorial. 

Thanks in advance for any reply.

Piotrek

**Comment by Steffan153** [comment]
It would be nice if it didn't auto-reload on every keystroke, my browser chokes on that.
Also, it would be nice if I could move the preview to the bottom.

**Comment by Steffan153** [comment]
* The account link is broken.
* Since you use CodeMirror, how about bracket auto-closing and HTML element auto-closing?
* Also, would be nice if CodeMirror had the emmet plugin.
* Great work! :tada:

**Comment by curran** [comment]
@Steffan153 Nice! Thank you for this feedback. These are all great directions for improvement.

Re: on every keystroke - it actually waits for you to stop typing for some amount of time, then re-runs, but I get your point. I was thinking to make an option for turning off "auto-run", so that you could do something explicit to trigger a run, like hit "Shift + Enter" or something. Would that work well for you?

I'll have to look into the emmet plugin. I've never used it.

**Comment by Steffan153** [comment]
Emmet isn't a big deal since most of the time we're in JS. A refresh fixed the auto-reload thing so there's some auto-run bug.

 > I was thinking to make an option for turning off "auto-run", so that you could do something explicit to trigger a run, like hit "Shift + Enter" or something. Would that work well for you?

That was exactly what I was thinking of, great idea. :smiley:  

For moving the preview to the bottom, I noticed it automatically does that if you load the page with a smaller screen, but it would be nice if there was a toggle or something.

Looking forward to v2! :tada:

**Comment by mark0978** [comment]
Dark purple on black for the fork action?  Really?  Constrasting colors maybe?

**Comment by CodeAndWeb** [comment]
I am currently following your video on youtube.

The problem that I have is finding the right "Bowl of fruits" that you used as a starting point. There are about 20+ different versions of it - all of them more or less working - but it's hard to find the 'official' version.

I'd like to have a "refresh" button to restart the animation - yes - pressing enter somewhere in a file also does the job - but refresh would be great.

It would also be great if you could store the file changes in the browser - e.g. using locale storage - a browser refresh sends all changes to nil otherwise - which is quite frustrating.

**Comment by curran** [comment]
Greetings,

We've just launched VizHub 2.0 to https://vizhub.com/ which is super exciting! This contains a brand new design, so @mark0978 I hope you like it! I agree the purple on black was a poor color choice.

@CodeAndWeb Re: "refresh" button - I todally agree. This item is tracked here [Feature Request: Disable Auto-Run](https://discourse.vizhub.com/t/feature-request-disable-auto-run/35). It's the thing that the most people have asked for by far, and I hope to make progress on it soon. Also, the mechanism of saving has changed completely, so the losing of changes and problems with multiple tabs open that VizHub 1.0 had should be gone in VizHub 2.0 (it acts more like Google Docs, saving changes in real-time and keeping all open tabs in sync).

I think I'll close this issue now, as the discussions have moved to:

 * [VizHub User Forum](https://discourse.vizhub.com/)
 * [D3 Slack](https://d3-slackin.herokuapp.com/) #vizhub channel

**Comment by pablocenfo** [comment]
hello Curran, just doing my first setps on D3, was trying to upload a JSON file, however there's no option to "upload dataset"  option anymore, how can I upload a JSON file?

**Comment by curran** [comment]
Indeed, the feature was removed in VizHub 2.0, in favor of storing data elsewhere, such as in a GitHub Gist. Here's a video that shows how you can upload data to GitHub Gist: https://youtu.be/8tJV3jMHyEQ?t=411
