### ISSUE TITLE
Directories (File Folders in IDE)

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-ui#62]
As a visualization author, I want to put files in directories, so that I can scale the complexity of the code while maintaining sane organization.

Please :+1: this issue to help prioritize this task in our [backlog](https://github.com/datavis-tech/vizhub-ui/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by mutawa** [comment]
Adding folders in VizHub will enhance my experience as a developer. Please include them.

**Comment by curran** [comment]
Closing in favor of https://discourse.vizhub.com/t/feature-request-directories/38

Directories are working! Just add slashes to the file names.
